name: .NET, React CI/CD workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-business:
    runs-on: ubuntu-latest
    env:
      DB_SA_PASSWORD: ${{ secrets.DB_SA_PASSWORD }}
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          SA_PASSWORD: $DB_SA_PASSWORD
          ACCEPT_EULA: Y
        ports:
          - 1433
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore BookClubApp.Business/BookClubApp.Business.csproj

      - name: Build
        run: dotnet build BookClubApp.Business/BookClubApp.Business.csproj --no-restore

      - name: Run MSSQL Server Docker Container
        run: docker run --rm -d -p 1433:1433 -e SA_PASSWORD=$DB_SA_PASSWORD -e ACCEPT_EULA=Y mcr.microsoft.com/mssql/server:2022-latest

      - name: Setup MSSQL Server
        run: sleep 30s

      - name: Install EF Core Tools
        run: dotnet tool install --global dotnet-ef --version 7.0.14

      - name: Run migrations
        run: dotnet ef database update --project BookClubApp.DataAccess/BookClubApp.DataAccess.csproj

      - name: Restore dependencies (Test)
        run: dotnet restore BookClubApp.Business/Tests/BookClubApp.Business.Tests/BookClubApp.Business.Tests.csproj

      - name: Run unit and integration test
        run: dotnet test BookClubApp.Business/Tests/BookClubApp.Business.Tests/BookClubApp.Business.Tests.csproj --no-restore

  build-and-test-data-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore BookClubApp.DataAccess/BookClubApp.DataAccess.csproj

      - name: Build
        run: dotnet build BookClubApp.DataAccess/BookClubApp.DataAccess.csproj --no-restore

      - name: Restore dependencies (Test)
        run: dotnet restore BookClubApp.DataAccess/Tests/BookClubApp.DataAccessLayer.Tests/BookClubApp.DataAccessLayer.Tests.csproj

      - name: Run test
        run: dotnet test BookClubApp.DataAccess/Tests/BookClubApp.DataAccessLayer.Tests/BookClubApp.DataAccessLayer.Tests.csproj --no-restore

  build-and-test-presentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies (Presentation)
        run: npm ci
        working-directory: BookClubApp.Presentation

      - name: Run Presentation Layer Tests
        run: npm test
        working-directory: BookClubApp.Presentation

      - name: Build Presentation Layer
        run: npm run build
        working-directory: BookClubApp.Presentation
